Add basic struct generation
The-Nazara-Project/Thanix pull request #1
Opened 2024-01-12 22:14 UTC by marv7000

# What does this PR change?

This PR adds a basic Rust struct generation by parsing a YAML schema using Serde and then reformatting the output.

Tick the applicable box:
- [x] Add new feature
- [ ] Security changes
- [ ] Tests
- [ ] Documentation changed
- [ ] General Maintenance

2024-01-12 23:52 UTC, ByteOtter commented on src/main.rs
> -        "{} \n(c) The Nezara Project. (github.com/The-Nezara/Project)\n
I knew I had a typo in there somewhere!

2024-01-13 00:04 UTC, ByteOtter requested changes
So I have looked over it and found that it panics on my machine.
Here's the shortened backtrace, maybe you can figure this one out:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/bindgen.rs:94:70
stack backtrace:
   0: rust_begin_unwind
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/result.rs:1651:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/result.rs:1076:23
   4: thanix::bindgen::gen
             at ./src/bindgen.rs:94:26
   5: thanix::main
             at ./src/main.rs:35:23
   6: core::ops::function::FnOnce::call_once
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Also I would like you to format the code using `cargo fmt` if not already done so. The workflow shows errors so if you could check that I would greatly appreciate this.

Apart from that, great work and thanks for the help!

2024-01-13 00:07 UTC, marv7000 commented
I think you just need to create the "output/" directory, that's an easy fix though.
I did run `cargo fmt` over it, but clippy will complain because most of the struct fields are still not marked with `#[allow(dead_code)]`.

2024-01-13 00:13 UTC, ByteOtter commented
> I think you just need to create the "output/" directory, that's an easy fix though. I did run `cargo fmt` over it, but clippy will complain because most of the struct fields are still not marked with `#[allow(dead_code)]`.

You were right that did the trick. Stupid that I didn't think of that. 🤦🏼 

Clippy will complain about dead code but as these are classified as warnings they can be ignored for now. But I did see real errors in the workflow output so maybe check tomorrow.

2024-01-13 00:17 UTC, marv7000 commented
Should work now, seems like `File::write` is not optimal.

2024-01-13 00:18 UTC, ByteOtter commented
Great work on fixing that this quickly. 
As this is a complete feature now, I would suggest we merge it tomorrow.
Would you say that adding some tests for this feature would be even possible? Not today of course ...

2024-01-13 00:19 UTC, marv7000 commented
Sure, I'll get to it.

2024-01-13 00:19 UTC, ByteOtter approved these changes

2024-01-14 12:56 UTC, ByteOtter approved these changes
LGTM. We're gonna rework the splitting  of these structs into different modules later.

2024-01-14 14:03 UTC, merged